§1. 前提条件

In [7]:
from scipy import sparse
import numpy as np

§2. 疎行列の作成（lil_matrix）

In [2]:
a = sparse.lil_matrix((5,5))
a[0,0]=1; a[1,2]=2; a[3,4]=3; a[4,4]=4;
a

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in LInked List format>

§3. 密行列への変換

In [3]:
a.todense()

matrix([[ 1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  2.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  3.],
        [ 0.,  0.,  0.,  0.,  4.]])

§4. Matrix変換

In [4]:
b = a.tocsr()
b

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

§5. 密行列への変換（特定データ）

In [5]:
b.getrow(1).todense()

matrix([[ 0.,  0.,  2.,  0.,  0.]])

In [9]:
v = np.array([1,2,3,4,5])
a.dot(v)

array([  1.,   6.,   0.,  15.,  20.])